# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'firstui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(458, 213)
        Form.setMinimumSize(QtCore.QSize(458, 213))
        Form.setMaximumSize(QtCore.QSize(458, 213))
        self.setting_btn = QtWidgets.QPushButton(Form)
        self.setting_btn.setGeometry(QtCore.QRect(400, 100, 151, 55))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.setting_btn.setFont(font)
        self.setting_btn.setObjectName("setting_btn")
        self.information_btn = QtWidgets.QPushButton(Form)
        self.information_btn.setGeometry(QtCore.QRect(400, 180, 151, 55))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.information_btn.setFont(font)
        self.information_btn.setObjectName("information_btn")
        self.start_btn = QtWidgets.QPushButton(Form)
        self.start_btn.setGeometry(QtCore.QRect(400, 260, 151, 55))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.start_btn.setFont(font)
        self.start_btn.setObjectName("start_btn")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(400, 340, 151, 55))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "CNC_UI"))
        self.setting_btn.setText(_translate("Form", "Settings"))
        self.information_btn.setText(_translate("Form", "Informations"))
        self.start_btn.setText(_translate("Form", "Start"))
        self.pushButton.setText(_translate("Form", "Exit"))
