# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mapui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.map_back = QtWidgets.QPushButton(self.widget)
        self.map_back.setGeometry(QtCore.QRect(20, 40, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.map_back.setFont(font)
        self.map_back.setMinimumSize(80, 30)  # Adjust the size as needed
        self.map_back.setObjectName("map_back")
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setGeometry(QtCore.QRect(200, 40, 591, 521))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.map_label = QtWidgets.QLabel(self.frame)
        self.map_label.setGeometry(QtCore.QRect(100, 240, 54, 12))
        self.map_label.setObjectName("map_label")
        Form.setCentralWidget(self.widget)
        self.menubar = QtWidgets.QMenuBar(Form)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        Form.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Form)
        self.statusbar.setObjectName("statusbar")
        Form.setStatusBar(self.statusbar)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.map_back.setText(_translate("Form", "Back"))
        self.map_label.setText(_translate("Form", "TextLabel"))
